name: мій другий міні тест сайпреса та гіт хаба

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout (клонування коду репозиторію)
        uses: actions/checkout@v3
      - name: Cypress run (Запуск тестів Cypress)
        uses: npx cypress run --headless --browser chrome
        # uses: cypress-io/github-action@v5
