name: мій 5-й тест сайпреса та гіт хаба

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Cypress install
        run: npx cypress install --cache-path $HOME/.cache/Cypress

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        run: npm run cy:run

      - name: Capture screenshot
        run: |
          mkdir screenshots
          mv cypress/screenshots/*.png screenshots/

      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: Screenshots
          path: screenshots/

      - name: Upload exit code
        uses: actions/upload-artifact@v2
        with:
          name: Exit Code
          path: exit_code.txt
