name: мій 5-й тест сайпреса та гіт хаба

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        run: |
          if [ ! -d "$HOME/.cache/Cypress" ]; then
            mkdir -p $HOME/.cache/Cypress
          fi
          sudo chown -R $USER:$USER $HOME/.cache/Cypress
          npx cypress install
          npm ci

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          browser: chrome

      - name: Capture screenshot (Знімок екрана)
        run: |
          mkdir screenshots
          mv cypress/screenshots/*.png screenshots/

      - name: Upload screenshot (Завантаження знімка екрана)
        uses: actions/upload-artifact@v2
        with:
          name: Screenshots
          path: screenshots/

      - name: Upload exit code (Завантаження вихідного коду)
        uses: actions/upload-artifact@v2
        with:
          name: Exit Code
          path: exit_code.txt
